### ISSUE TITLE
Return blank in GeoIP

### ISSUE THREAD

**Issue by guptahanu** [magento-hackathon/Sandfox_GeoIP#26]
$geoIP->getCountry() print blank issue

**Comment by to8gal** [comment]
here too, no info from geoIP

**Comment by richardgrantham26** [comment]
same for me too

**Comment by sprankhub** [comment]
It can always happen that the current IP is not known in the database. Ideas:
1. The `var/geoip` folder is not writable, so that the file cannot be fetched from MaxMind.
2. The current IP is not included in the MaxMind database.
   1. The current IP is a IPv6 IP. These are not included in the currently used MaxMind database. This will be fixed with #25.

If there is any consistent way to reproduce this issue, please re-open and tell us the necessary steps.

**Comment by to8gal** [comment]
I abandoned for another solution long ago, so need to reproduce any step

But thanks
